spring:
  application:
    name: gatewayserver

  cloud:
    config:
      uri: http://configserver:8071
    compatibility-verifier:
      enabled: false
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.example: DEBUG