spring:
  application:
    name: gatewayserver

  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: licensing-service
          uri: http://localhost:8081
          predicates:
            - Path=/static/**