services:
  licensing-service:
    image: docker.io/library/licensing-service:0.0.1-SNAPSHOT

    ports:
      - "8080:8080"

    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URI = http://localhost:8071"

