spring:
  application:
    name:
      licensing-service
  #profiles:
    #active:
      #dev

  mvc:
    static-path-pattern: /static/**

  #main:
    #allow-bean-definition-overriding: true
  #cloud:
    #compatibility-verifier:
      #enabled: false

  #management.endpoints.enabled-by-default: false
#management.endpoint.health:
  #enabled: true
  #show-details: always