spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    compatibility-verifier:
      enabled: false
  config:
    import: "optional:configserver:http://configserver:8071"

  application:
    name: licensing-service

  profiles:
    active: dev

management.endpoints.enabled-by-default: false
management.endpoint.health:
  enabled: true
  show-details: always