spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/license-service
    #url: jdbc:postgresql://localhost:5432/license-service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/
      #defaultZone: http://localhost:8070/eureka/

