spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/license-service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

#eureka:
  #instance:
    #preferIpAddress: true
  #client:
    #registerWithEureka: true
    #fetchRegistry: true
    #serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/