spring:
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    database: POSTGRESQL

  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: org.postgresql.Driver

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

    enabled-by-default: true