services:
  database:
    image: postgres:latest

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "licensing_service"

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql

    networks:
      backend:
        aliases:
          - "database"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    image: docker.io/library/config-server:0.0.1-SNAPSHOT

    ports:
      - "8071:8071"

    networks:
      backend:
        aliases:
          - "config-server"

  eureka-server:
    image: docker.io/library/eureka-server:0.0.1-SNAPSHOT

    ports:
      - "8761:8761"

    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started

    networks:
      backend:
        aliases:
          - "eureka-server"

  gateway-server:
    image: docker.io/library/gateway-server:0.0.1-SNAPSHOT

    ports:
      - "8072:8072"

    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://localhost:8071"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://localhost:8761/eureka/"

    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started

    networks:
      backend:
        aliases:
          - "gateway-server"

  licensing-service:
    image: docker.io/library/licensing-service:0.0.1-SNAPSHOT

    ports:
      - "8180:8080"

    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://localhost:8071"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/licensing_service"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "123456"
      CONFIGSERVER_PORT: "8071"
      DATABASESERVER_PORT: "5432"

    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started

    networks:
      - backend

  organization-service:
    image: docker.io/library/organization-service:0.0.1-SNAPSHOT

    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://localhost:8071"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/licensing_service"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "123456"
      CONFIGSERVER_PORT: "8071"
      DATABASESERVER_PORT: "5432"

    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started

    ports:
      - "8081:8081"

    networks:
      - backend




networks:
  backend:
    driver: bridge