spring:
  application:
    name: organization-service

  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:8071

  datasource:
    url: jdbc:postgresql://localhost:5432/licensing_service
    username: postgres
    password: 123456

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG
