spring:
  cloud:
    compatibility-verifier:
      enabled: false

  application:
    name: organization-service

  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:8071

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/licensing_service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
