spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/licensing_service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect